# Generated by Django 3.2.25 on 2024-07-11 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created Date')),
                ('vin_number', models.CharField(default='Нет информации', max_length=17, unique=True)),
                ('body_number', models.CharField(default='Нет информации', max_length=20)),
                ('chassis_number', models.CharField(default='Нет информации', max_length=50)),
                ('license_number', models.CharField(default='Нет информации', max_length=6)),
                ('license_region', models.CharField(default='Нет информации', max_length=3)),
                ('model', models.CharField(default='Нет информации', max_length=50)),
                ('brand', models.CharField(default='Нет информации', max_length=50)),
                ('manufacture_year', models.CharField(default='Нет информации', max_length=4)),
                ('vehicle_category', models.CharField(default='Нет информации', max_length=3)),
                ('vehicle_category_tr', models.CharField(default='Нет информации', max_length=10)),
                ('min_weight', models.CharField(default='Нет информации', max_length=6)),
                ('max_weight', models.CharField(default='Нет информации', max_length=6)),
                ('power_hp', models.CharField(default='Нет информации', max_length=8)),
                ('fuel_type', models.CharField(default='Нет информации', max_length=10)),
                ('brake_system', models.CharField(default='Нет информации', max_length=20)),
                ('document_type_sts', models.CharField(default='Нет информации', max_length=10)),
                ('document_series', models.CharField(default='Нет информации', max_length=4)),
                ('document_number', models.CharField(default='Нет информации', max_length=6)),
                ('document_date', models.CharField(default='Нет информации', max_length=10)),
                ('document_maker', models.CharField(default='Нет информации', max_length=20)),
                ('color', models.CharField(default='Нет информации', max_length=20)),
                ('vehicle_type', models.CharField(default='Нет информации', max_length=50)),
                ('engine_capacity', models.CharField(default='Нет информации', max_length=10)),
                ('engine_number', models.CharField(default='Нет информации', max_length=8)),
                ('pts_series_number', models.CharField(default='Нет информации', max_length=20)),
                ('pts_maker', models.CharField(default='Нет информации', max_length=20)),
                ('pts_owner', models.CharField(default='Нет информации', max_length=3)),
                ('hijacking', models.TextField(default='Нет информации')),
                ('report_path', models.FilePathField(default=None, null=True)),
            ],
            options={
                'db_table': 'cars',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_type', models.CharField(choices=[('US', 'User'), ('VIP', 'VIP'), ('SUP', 'Support'), ('AD', 'Admin')], default='US', max_length=3, verbose_name='User Type')),
                ('subscription_expired_date', models.DateField(default=None, null=True, verbose_name='Subcription Expired Date')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Registration Date')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='VehicleLimits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created Date')),
                ('description', models.TextField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='carscan.car')),
            ],
            options={
                'db_table': 'vehicles_limits',
            },
        ),
        migrations.CreateModel(
            name='UserCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carscan.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carscan.user')),
            ],
            options={
                'db_table': 'UsersCars',
            },
        ),
        migrations.CreateModel(
            name='RegistrationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created Date')),
                ('period', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_history', to='carscan.car')),
            ],
            options={
                'db_table': 'registrations_histories',
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created Date')),
                ('dc_number', models.CharField(max_length=15)),
                ('dc_validity_date', models.CharField(max_length=40)),
                ('mileage', models.IntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspetions', to='carscan.car')),
            ],
            options={
                'db_table': 'inspections',
            },
        ),
        migrations.CreateModel(
            name='Fines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created Date')),
                ('description', models.TextField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='carscan.car')),
            ],
            options={
                'db_table': 'fines',
            },
        ),
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created Date')),
                ('img_path', models.FilePathField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accidents', to='carscan.car')),
            ],
            options={
                'db_table': 'accidents',
            },
        ),
    ]
